### ISSUE TITLE
Add span to price symbol

### ISSUE THREAD

**Issue by newcodesmith** [searchspring/snap#1025]
It would be nice to have the price symbol in its own span so that styling can be applied such as spacing and font size changes from the rest of the price.

**Comment by korgon** [comment]
This should be possible but will require some changes to the component that will hopefully not cause issues with backwards compatibility.

Since the `currency` filter typically does the string manipulation that outputs the final price string (eg: $4.99) it will be a little tricky to split out the currency symbol (since we are currently taking this string output from the filter and rendering it). The component will have to be made responsible for handling the `symbol` and `symbolAfter` props directly instead of passing them off to the filter - the filter would no longer handle the symbol at all.
