### ISSUE TITLE
Infinite Backfill

### ISSUE THREAD

**Issue by korgon** [searchspring/snap#632]
Customers using the `infinite` setting in the search controller are needing to backfill up to 10+ pages. To better handle the backfill in these scenarios, we will need to change the way we are doing the backfill. Currently the backfill is done by requesting the pages needed separately and awaiting the responses from those requests. This works well when the customer has the responses in the session storage cache, but when that cache does not exist or is expired this leads to multiple requests to the API.

To handle the backfill better we could request up to 500 products per page until we have backfilled to the current page. This would mean knowing the default results per page, and making the appropriate number of requests to get the results we need.

For example, a site with a default per page of 24, with the current pagination `page` at 10 would normally require 10 requests to backfill. With the proposed change we would instead make a single request with a perPage request parameter at 240. If the `page` was at 30 the number of results needed would be 720 - this is beyond our API limit of 500 results per page. To get these results we would need to fetch twice, one page at 500 perPage, and one at 220 perPage. Doing these calculations to change the perPage may be unnecessary - it may be easier to simply fetch 500 results per page when backfilling, and then slicing off the number of results as needed.

**Comment by chrisFrazier77** [comment]
Waiting on Kevins opinion on how we should handle backfill functionality now that we can fetch 500 products at a time. Does it still make sense to even have a backfill setting? Current functionality is when requesting a page higher than backfill setting, it resets back to page one, is that functionality we wish to maintain? or since we no longer need to fetch each page individually does it make more sense to allow fetching past the backfill setting. ex: backfill 3, but refresh on page 4, should that go back to page 1? or just fetch everything up to page 4? or fetch 4 and the previous 3 pages? 

Maybe it makes more sense for us to change backfill setting to a boolean just to enable the functionality and then have some hardcoded set request limit in snap since we know each request is 500 products at a max.

**Comment by dkonieczek** [comment]
After thinking about this some more, since we already have clients using this I think we should keep the current functionality and have this ticket just be about consolidating the multiple API requests
