### ISSUE TITLE
Some global settings not working in Autocomplete controller

### ISSUE THREAD

**Issue by adriamurphy** [searchspring/snap#802]
[According to Snap API docs](https://searchspring.github.io/snap/#/api-docs), for Autocomplete we should be able to set `limit` and `valueLimit` as `globals` for `facets`. I tried setting both of these parameters to an Autocomplete controller with no luck. Other parameters like `include` and `exclude` do seem to work.

It would be nice to get these working so we can limit the amount of data returned in the Autocomplete response.

**Comment by korgon** [comment]
@adriamurphy Unfortunately these parameters do not really exist yet... this is due to the fact that the Snap API specification is not yet implemented. We could perhaps implement these in our temporary "transforms", but it wouldn't actually make the API response smaller since these are not valid API parameters on the current (production) API.
